### ISSUE TITLE
Dynamic Authentication to SteelConnect

### ISSUE THREAD

**Issue by mirrexagon** [narcs/steelconnect-dialogflow#2]
I'm not entirely sure, but it looks like the credentials used are hardcoded per app instance. It would be nice to be able to give your credentials to the DialogFlow agent (chatbot or whatever) and have it use them.

Of course, there are security considerations, but there's already some hardcoded credentials anyway (see #1) - just don't use this in actual production!

---

The client has told us that Google auth isn't planned for a while, but that it would be good to have a placeholder system to easily integrate it when it does come.

We should consider designing with different auth methods in mind.

**Comment by leesimond** [comment]
We'll put this on the agenda for next client meeting.

**Comment by mirrexagon** [comment]
The client has suggested maybe using Firebase services to link a Google ID to SCM credentials, SCM instance URLs and maybe org IDs within those instances.

_It looks like Firebase provides both authentication and database services that can be tied to a Google cloud project.  So maybe it can be used to log a user on based on their Google ID and then map that back to the SCM authentication information stored in the Firebase database for that user.  And if there are multiple URLs associated then we can allow the user to select which one they want to authenticate to._

**Comment by mirrexagon** [comment]
From https://firebase.google.com/docs/auth/users

"A Firebase User has a fixed set of basic properties—a unique ID, a primary email address, a name and a photo URL—stored in the project's user database, that can be updated by the user (iOS, Android, web). You cannot add other properties to the Firebase User object directly; instead, **you can store the additional properties in your Firebase Realtime Database.**"

**Comment by mirrexagon** [comment]
We have more notes in our Client Meeting 04/05/2018 meeting notes.
